[package]
edition = "2018"
build = "../common/build/build.rs"
name = "validator_session"
version = "0.0.1"

[dependencies]
# domestic
catchain = { path = "../catchain" }
ever-crypto = { git = "ssh://git@github.com/tonlabs/ever-crypto.git" }
storage = { path = "../storage" }
ton_api = { git = "ssh://git@github.com/tonlabs/ton-tl.git", package = "ton_api" }
ton_block = { git = "ssh://git@github.com/tonlabs/ton-block.git" }
ton_types = { git = "ssh://git@github.com/tonlabs/ton-types.git" }

# external
backtrace = "0.3"
crc = "3.0"
crossbeam = "0.7"
failure = "0.1"
hex = "0.4"
lazy_static = "1.4"
log = "0.4"
metrics-core = "0.5"
metrics-runtime = "0.13"
rand = "0.8"
sha2 = "0.9"

[dev-dependencies]
env_logger = "0.7"
chrono = "0.4"
colored = "1.9"
