[package]
edition = "2021"
build = "../common/build/build.rs"
name = "catchain"
version = "0.1.0"

[dependencies]
# external
base64 = "0.13"
chrono = "0.4.10"
crossbeam = "0.7.3"
ed25519-dalek = "1.0"
failure = "0.1"
futures = "0.3.4"
hex = "0.4"
lazy_static = "1.4.0"
log = "0.4"
metrics-core = "0.5.2"
metrics-runtime = "0.13.0"
rand = "0.8"
regex = "1.3.1"
sha2 = "0.9"
tokio = { version = "1.5", features = ["rt-multi-thread"] }

adnl = { git = "ssh://git@github.com/tonlabs/adnl.git", features = ["node"] }
ever-crypto = { git = "ssh://git@github.com/tonlabs/ever-crypto.git" }
overlay = { git = "ssh://git@github.com/tonlabs/overlay.git" }
rldp = { git = "ssh://git@github.com/tonlabs/rldp.git" }
storage = { path = "../storage" }
ton_api = { git = "ssh://git@github.com/tonlabs/ton-tl.git", package = "ton_api" }
ton_types = { git = "ssh://git@github.com/tonlabs/ton-types.git" }

[dev-dependencies]
env_logger = "0.7.1"
chrono = "0.4.10"
pretty_assertions = "1.2"

[target.'cfg(windows)'.dev-dependencies.rocksdb]
git = "https://github.com/rust-rocksdb/rust-rocksdb.git"

[target.'cfg(unix)'.dev-dependencies.rocksdb]
git = "https://github.com/rust-rocksdb/rust-rocksdb.git"
features = ["jemalloc"]

[features]
default = []
export_key = ["ever-crypto/export_key"]
